#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConTrol_TrangThaiPhong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nhaTro")]
	public partial class dataPhong_LinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPHONGTRO(PHONGTRO instance);
    partial void UpdatePHONGTRO(PHONGTRO instance);
    partial void DeletePHONGTRO(PHONGTRO instance);
    #endregion
		
		public dataPhong_LinQDataContext() : 
				base(global::ConTrol_TrangThaiPhong.Properties.Settings.Default.nhaTroConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dataPhong_LinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataPhong_LinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataPhong_LinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataPhong_LinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PHONGTRO> PHONGTROs
		{
			get
			{
				return this.GetTable<PHONGTRO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGTRO")]
	public partial class PHONGTRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPT;
		
		private string _MaKV;
		
		private string _MaBangGia;
		
		private string _TenPhong;
		
		private System.Nullable<int> _SLToiDa;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<bool> _TrangThaiThue;
		
		private System.Nullable<int> _SoNguoiHienTai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPTChanging(string value);
    partial void OnMaPTChanged();
    partial void OnMaKVChanging(string value);
    partial void OnMaKVChanged();
    partial void OnMaBangGiaChanging(string value);
    partial void OnMaBangGiaChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnSLToiDaChanging(System.Nullable<int> value);
    partial void OnSLToiDaChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnTrangThaiThueChanging(System.Nullable<bool> value);
    partial void OnTrangThaiThueChanged();
    partial void OnSoNguoiHienTaiChanging(System.Nullable<int> value);
    partial void OnSoNguoiHienTaiChanged();
    #endregion
		
		public PHONGTRO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPT", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPT
		{
			get
			{
				return this._MaPT;
			}
			set
			{
				if ((this._MaPT != value))
				{
					this.OnMaPTChanging(value);
					this.SendPropertyChanging();
					this._MaPT = value;
					this.SendPropertyChanged("MaPT");
					this.OnMaPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKV", DbType="NVarChar(50)")]
		public string MaKV
		{
			get
			{
				return this._MaKV;
			}
			set
			{
				if ((this._MaKV != value))
				{
					this.OnMaKVChanging(value);
					this.SendPropertyChanging();
					this._MaKV = value;
					this.SendPropertyChanged("MaKV");
					this.OnMaKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBangGia", DbType="NVarChar(50)")]
		public string MaBangGia
		{
			get
			{
				return this._MaBangGia;
			}
			set
			{
				if ((this._MaBangGia != value))
				{
					this.OnMaBangGiaChanging(value);
					this.SendPropertyChanging();
					this._MaBangGia = value;
					this.SendPropertyChanged("MaBangGia");
					this.OnMaBangGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(50)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLToiDa", DbType="Int")]
		public System.Nullable<int> SLToiDa
		{
			get
			{
				return this._SLToiDa;
			}
			set
			{
				if ((this._SLToiDa != value))
				{
					this.OnSLToiDaChanging(value);
					this.SendPropertyChanging();
					this._SLToiDa = value;
					this.SendPropertyChanged("SLToiDa");
					this.OnSLToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiThue", DbType="Bit")]
		public System.Nullable<bool> TrangThaiThue
		{
			get
			{
				return this._TrangThaiThue;
			}
			set
			{
				if ((this._TrangThaiThue != value))
				{
					this.OnTrangThaiThueChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiThue = value;
					this.SendPropertyChanged("TrangThaiThue");
					this.OnTrangThaiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNguoiHienTai", DbType="Int")]
		public System.Nullable<int> SoNguoiHienTai
		{
			get
			{
				return this._SoNguoiHienTai;
			}
			set
			{
				if ((this._SoNguoiHienTai != value))
				{
					this.OnSoNguoiHienTaiChanging(value);
					this.SendPropertyChanging();
					this._SoNguoiHienTai = value;
					this.SendPropertyChanged("SoNguoiHienTai");
					this.OnSoNguoiHienTaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
